$(document).ready(function(){

    var contacts = new Map();
    var json = '[{"fullName":"Rachna Saluja","emailId":"rachnasaluja@gmail.com","userId":1,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Arjun Shah","emailId":"arjunshah@gmail.com","userId":2,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"AneesM","emailId":"aneesm@gmail.com","userId":3,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Rajat Tripathi","emailId":"coolboy@gmail.com","userId":4,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Deeksha Agrawal","emailId":"deekshaagrawal@gmail.com","userId":5,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Utkarsha Gaumat","emailId":"utkarshagaumat@gmail.com","userId":6,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Riya Tilwani","emailId":"riyatilwani@gmail.com","userId":7,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Rohan Adhyapak","emailId":"rohanadhyapak@gmail.com","userId":8,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Asish Kona","emailId":"ashishkona@gmail.com","userId":9,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Aditya Ramanathan","emailId":"adityaramanathan@gmail.com","userId":10,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Harsh Shrivastava","emailId":"harshshrivastava@gmail.com","userId":11,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Harsh Tyagi","emailId":"harshtyagi@gmail.com","userId":12,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Deeksha Rathi","emailId":"deeksharathi@gmail.com","userId":13,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"Rohan Anand","emailId":"rohananand@gmail.com","userId":14,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]},{"fullName":"ArjunRathee","emailId":"arjunrathee@gmail.com","userId":15,"password":"","phoneNo":12345,"profilePictureURL":"","chatContacts":[]}]';
    json = JSON.parse(json);
    json.forEach(function(contact){
            contacts[contact["emailId"]] = contact;
            console.log(contacts);
        });
    var user = getLocalStorage("thisUser");
    contacts[user.emailId] = user;
     localStorage.setItem("allUsers", JSON.stringify(contacts));
});